name: Complex App

on:
  push:
    paths:
    - 'complex/**'
    - '.github/workflows/complex.yml'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          path: complex/backend
          repository: vgalilei/getpython/cats
          tag_with_ref: true

  deploy:
    name: Deploy complex to production
    runs-on: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:
        run: |
          cd complex;
          docker-compose build
          docker-compose up -d
